// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using income_verifier.Data;

#nullable disable

namespace income_verifier.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250618234727_AddSecond")]
    partial class AddSecond
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("income_verifier.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasDiscriminator<string>("ClientType").HasValue("Client");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("income_verifier.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupportYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DiscountId = 1,
                            EndDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            IsSigned = true,
                            Price = 5000m,
                            SoftwareId = 1,
                            SoftwareVersion = "1.0.0",
                            StartDate = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            SupportYears = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 3,
                            EndDate = new DateTime(2027, 6, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            IsSigned = false,
                            Price = 12000m,
                            SoftwareId = 2,
                            SoftwareVersion = "2.5.1",
                            StartDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            SupportYears = 2
                        });
                });

            modelBuilder.Entity("income_verifier.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Spring Promo",
                            Percentage = 0.10m,
                            StartDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Summer Sale",
                            Percentage = 0.20m,
                            StartDate = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("income_verifier.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000m,
                            ContractId = 1,
                            PaymentDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 6000m,
                            ContractId = 2,
                            PaymentDate = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("income_verifier.Models.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Software");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Business",
                            CurrentVersion = "1.0.0",
                            Description = "Sample software 1",
                            Name = "SuperApp",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Utility",
                            CurrentVersion = "2.5.1",
                            Description = "Sample software 2",
                            Name = "MegaTool",
                            Price = 12000m
                        });
                });

            modelBuilder.Entity("income_verifier.Models.CompanyClient", b =>
                {
                    b.HasBaseType("income_verifier.Models.Client");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Krs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasIndex("Krs")
                        .IsUnique()
                        .HasFilter("[Krs] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Address = "Business Road 10",
                            Email = "info@acmecorp.com",
                            Phone = "555666777",
                            CompanyName = "Acme Corp",
                            Krs = "0000111122"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tech Park 5",
                            Email = "contact@techsolutions.com",
                            Phone = "888999000",
                            CompanyName = "Tech Solutions",
                            Krs = "9999888877"
                        });
                });

            modelBuilder.Entity("income_verifier.Models.IndividualClient", b =>
                {
                    b.HasBaseType("income_verifier.Models.Client");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasIndex("Pesel")
                        .IsUnique()
                        .HasFilter("[Pesel] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Individual");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Main Street 1",
                            Email = "john.doe@email.com",
                            Phone = "111222333",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            Pesel = "12345678901"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Second Avenue 2",
                            Email = "anna.smith@email.com",
                            Phone = "444555666",
                            FirstName = "Anna",
                            IsDeleted = false,
                            LastName = "Smith",
                            Pesel = "98765432109"
                        });
                });

            modelBuilder.Entity("income_verifier.Models.Contract", b =>
                {
                    b.HasOne("income_verifier.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("income_verifier.Models.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("income_verifier.Models.Software", "Software")
                        .WithMany("Contracts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Discount");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("income_verifier.Models.Payment", b =>
                {
                    b.HasOne("income_verifier.Models.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("income_verifier.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("income_verifier.Models.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("income_verifier.Models.Software", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
